plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.8'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.graalvm.buildtools.native' version '1.1.14'
}

group = 'org.Roclh'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
        nativeImageCapable = false
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'

    implementation 'org.xerial:sqlite-jdbc:3.49.1.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects:7.2.24.Final'

    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

graalvmNative {
    binaries {
        main {
            imageName = 'pohr'
            mainClass = 'org.Roclh.PohrApplication'
            buildArgs.add('--no-fallback')
            buildArgs.add('-H:+ReportExceptionStackTraces')
            buildArgs.add('-H:+AddAllCharsets')
            buildArgs.add('-J-Xmx12g')                // было 4g
            buildArgs.add('-H:NumberOfThreads=20')    // явно, чтобы плагин не переопределил
            runtimeArgs.add('--enable-native-access=ALL-UNNAMED')
        }
    }
}

test {
    useJUnitPlatform()
}