spring:
  application:
    name: pohr
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  datasource:
    url: jdbc:sqlite:./data/pohr.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8080