xray:
  home: /app/xray
  install:
    auto: ${XRAY_AUTO_INSTALL:true}
    version: ${XRAY_VERSION:latest}
    download-url-template: https://github.com/XTLS/Xray-core/releases/download/v{version}/Xray-{platform}.zip
    fallback-url-template: ${XRAY_FALLBACK_URL:}
  server:
    host: ${XRAY_HOST:}
  reality:
    dest: ${XRAY_REALITY_DEST:www.microsoft.com:443}
    server-names: ${XRAY_REALITY_SNI:www.microsoft.com}

pohr:
  scripts:
    home: ${SCRIPTS_HOME:/app/scripts}