package org.Roclh.service.edge;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.Roclh.model.edge.EdgeConfig;
import org.Roclh.model.edge.EdgeRoute;
import org.Roclh.model.edge.EdgeSite;
import org.Roclh.repository.edge.EdgeConfigRepository;
import org.Roclh.repository.edge.EdgeRouteRepository;
import org.Roclh.repository.edge.EdgeSiteRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class EdgeConfigService {

    private static final String DEFAULT_CONFIG = "default";

    private final EdgeConfigRepository cfgRepo;
    private final EdgeRouteRepository routeRepo;
    private final EdgeSiteRepository siteRepo;

    @Value("${pohr.edge.home}")
    private String edgeHome;

    public Path nginxConfigPath() {
        return Path.of(edgeHome, "edge", "nginx.conf");
    }

    public Path caddyConfigPath() {
        return Path.of(edgeHome, "edge", "Caddyfile");
    }

    public EdgeConfig getConfig() {
        return cfgRepo.findById(DEFAULT_CONFIG)
                .orElseThrow(() -> new IllegalStateException("edge_config 'default' row missing"));
    }

    // =====================================================================
    // nginx stream config
    // =====================================================================

    /**
     * Возвращает конфиг ровно в том виде, в каком он был на хосте:
     * map + именованные upstream-блоки + server { ssl_preread on; }.
     */
    public String buildNginxConfig() {
        EdgeConfig c = getConfig();
        List<EdgeRoute> routes = routeRepo.findByEnabledTrueOrderBySortOrderAsc();

        // Собираем уникальные upstream: name -> "host:port"
        Map<String, String> upstreams = new LinkedHashMap<>();
        for (EdgeRoute r : routes) {
            String name = upstreamName(r.getTargetHost(), r.getTargetPort());
            upstreams.putIfAbsent(name, r.getTargetHost() + ":" + r.getTargetPort());
        }
        String fallbackName = upstreamName(c.getFallbackTarget());
        upstreams.putIfAbsent(fallbackName, c.getFallbackTarget());

        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by Pohr. Do not edit manually.\n");
        sb.append("worker_processes ").append(c.getWorkerProcesses()).append(";\n");
        sb.append("pid ").append(Path.of(edgeHome, "edge", "nginx.pid")).append(";\n");
        sb.append("error_log stderr warn;\n");
        sb.append("events {\n");
        sb.append("    worker_connections ").append(c.getWorkerConnections()).append(";\n");
        sb.append("}\n\n");

        // http {} блок — только если пользователь ввёл extraHttpDirectives
        if (c.getExtraHttpDirectives() != null && !c.getExtraHttpDirectives().isBlank()) {
            sb.append("http {\n");
            for (String line : c.getExtraHttpDirectives().split("\\R")) {
                if (!line.isBlank()) sb.append("    ").append(line.strip()).append('\n');
            }
            sb.append("}\n\n");
        }

        sb.append("stream {\n");
        sb.append("    access_log off;\n\n");

        sb.append("    map $ssl_preread_server_name $pohr_upstream {\n");
        for (EdgeRoute r : routes) {
            sb.append("        ").append(r.getSni())
                    .append("  ").append(upstreamName(r.getTargetHost(), r.getTargetPort()))
                    .append(";\n");
        }
        sb.append("        default  ").append(fallbackName).append(";\n");
        sb.append("    }\n\n");

        for (Map.Entry<String, String> e : upstreams.entrySet()) {
            sb.append("    upstream ").append(e.getKey())
                    .append(" { server ").append(e.getValue()).append("; }\n");
        }
        sb.append("\n");

        sb.append("    server {\n");
        sb.append("        listen      ").append(c.getStreamPort()).append(";\n");
        sb.append("        listen      [::]:").append(c.getStreamPort()).append(";\n");
        sb.append("        proxy_pass  $pohr_upstream;\n");
        sb.append("        ssl_preread on;\n");
        sb.append("        proxy_timeout ").append(c.getStreamProxyTimeout()).append(";\n");
        sb.append("        proxy_connect_timeout ").append(c.getStreamConnectTimeout()).append(";\n");
        sb.append("    }\n");

        if (c.getExtraStreamDirectives() != null && !c.getExtraStreamDirectives().isBlank()) {
            sb.append('\n');
            for (String line : c.getExtraStreamDirectives().split("\\R")) {
                if (!line.isBlank()) sb.append("    ").append(line.strip()).append('\n');
            }
        }
        sb.append("}\n");
        return sb.toString();
    }

    // =====================================================================
    // Caddyfile
    // =====================================================================

    public String buildCaddyfile() {
        EdgeConfig c = getConfig();
        List<EdgeSite> sites = siteRepo.findByEnabledTrueOrderByDomainAsc();

        StringBuilder sb = new StringBuilder();
        sb.append("# Auto-generated by Pohr. Do not edit manually.\n\n");

        // ---- Global options block ----
        sb.append("{\n");
        sb.append("    https_port ").append(c.getHttpsPort()).append('\n');
        if (c.getHttpPort() != 80) {
            sb.append("    http_port ").append(c.getHttpPort()).append('\n');
        }
        if (!"on".equals(c.getAutoHttps())) {
            sb.append("    auto_https ").append(c.getAutoHttps()).append('\n');
        }
        sb.append("    admin localhost:2019\n");
        sb.append("    log {\n");
        sb.append("        output stderr\n");
        sb.append("        format console\n");
        sb.append("    }\n");
        sb.append("    storage file_system ")
                .append(Path.of(edgeHome, "edge", "caddy-data")).append('\n');

        sites.stream()
                .map(EdgeSite::getAcmeEmail)
                .filter(e -> e != null && !e.isBlank())
                .findFirst()
                .ifPresent(e -> sb.append("    email ").append(e).append('\n'));

        if (c.getExtraGlobalDirectives() != null && !c.getExtraGlobalDirectives().isBlank()) {
            for (String line : c.getExtraGlobalDirectives().split("\\R")) {
                if (!line.isBlank()) sb.append("    ").append(line.strip()).append('\n');
            }
        }
        sb.append("}\n\n");

        // ---- Sites ----
        for (EdgeSite s : sites) {
            sb.append(s.getDomain()).append(" {\n");

            if (s.getBindAddress() != null && !s.getBindAddress().isBlank()) {
                sb.append("    bind ").append(s.getBindAddress()).append('\n');
            }

            if ("redirect".equals(s.getSiteType())) {
                String code = (s.getRedirectCode() == null || s.getRedirectCode().isBlank())
                        ? "permanent" : s.getRedirectCode();
                sb.append("    redir ").append(s.getRedirectTarget())
                        .append(' ').append(code).append('\n');
            } else {
                switch (s.getTlsMode()) {
                    case "acme" -> sb.append("    encode gzip\n");
                    case "internal" -> sb.append("    tls internal\n");
                    case "off" -> sb.append("    tls off\n");
                    default -> { /* noop */ }
                }
                sb.append("    reverse_proxy ")
                        .append(s.getUpstreamHost()).append(':').append(s.getUpstreamPort())
                        .append('\n');
            }

            if (s.getExtraDirectives() != null && !s.getExtraDirectives().isBlank()) {
                for (String line : s.getExtraDirectives().split("\\R")) {
                    if (!line.isBlank()) sb.append("    ").append(line.strip()).append('\n');
                }
            }
            sb.append("}\n\n");
        }
        return sb.toString();
    }

    public synchronized void materialize() {
        try {
            Path nginx = nginxConfigPath();
            Files.createDirectories(nginx.getParent());
            Files.writeString(nginx, buildNginxConfig(), StandardCharsets.UTF_8);
            Files.writeString(caddyConfigPath(), buildCaddyfile(), StandardCharsets.UTF_8);
            log.info("Edge configs materialized: {} + {}", nginx, caddyConfigPath());
        } catch (IOException e) {
            throw new IllegalStateException("Edge materialization failed", e);
        }
    }

    // =====================================================================
    // Helpers
    // =====================================================================

    /** "127.0.0.1:8443" -> "u_127_0_0_1_8443" — стабильное имя upstream-блока. */
    static String upstreamName(String host, int port) {
        return upstreamName(host + ":" + port);
    }

    static String upstreamName(String target) {
        return "u_" + target.replaceAll("[^A-Za-z0-9]", "_");
    }
}